apiVersion: argoproj.io/v1alpha1
kind: ConfigManagementPlugin
metadata:
  name: argo-bw-secrets-manifest
spec:
  generate:
    command: [sh, -c]
    args:
      - for i in *.yaml; do cat ${i}; echo "---"; done | argo-bw-secrets generate

  parameters:

  preserveFileMode: false