apiVersion: argoproj.io/v1alpha1
kind: ConfigManagementPlugin
metadata:
  name: argo-bw-secrets-helm
spec:
  init:
    command: [sh, -c]
    args:
      - test -f Chart.yaml && helm dependency build || exit 0
  generate:
    command: [sh, -c]
    args:
      - helm template $ARGOCD_APP_NAME -n $ARGOCD_APP_NAMESPACE --repo ${PARAM_HELM_REPO} --version ${PARAM_HELM_CHART_VERSION} ${PARAM_HELM_CHART} ${PARAM_HELM_ARGS} . | argocd-bw-secrets generate

  parameters:
    static:
      - name: helm-repo
        title: Helm Repo
        tooltip: Helm repository URL
        required: true
        itemType: "string"
        collectionType: "string"
        string: ""
      - name: helm-chart
        title: Helm Chart
        tooltip: Helm Chart
        required: true
        itemType: "string"
        collectionType: "string"
        string: ""
      - name: helm-chart-version
        title: Helm Chart Version
        tooltip: Helm Chart Version
        required: true
        itemType: "string"
        collectionType: "string"
        string: ""
      - name: helm-args
        title: Helm Arguments
        tooltip: Extra arguments to pass to Helm
        required: false
        itemType: "string"
        collectionType: "string"
        string: ""

  preserveFileMode: false