FROM golang:1.23 AS build
WORKDIR /workspace

COPY . .

RUN apt-get update && apt install musl-tools git ca-certificates -y
RUN go mod download

RUN CC=musl-gcc CGO_ENABLED=1 go build -trimpath -ldflags '-linkmode external -extldflags "-static -Wl,-unresolved-symbols=ignore-all"' .

FROM ubuntu:latest 

RUN apt-get update && apt install musl-tools ca-certificates -y; apt-get clean
RUN mkdir -p /home/argocd/cmp-server/config/

COPY cmp-manifest.yaml /home/argocd/cmp-server/config/plugin.yaml
COPY --from=build /workspace/argo-bw-secrets /usr/local/bin/argo-bw-secrets

ENTRYPOINT ["/var/run/argocd/argocd-cmp-server"]
